moviecollector/main_app/urls.py
from django.urls import path
from . import views
from main_app import views as main_app




urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('movies/', views.movies_index, name='index'),
    path('movies/<int:movies_id>/', views.movies_detail, name='detail'),
    path('movies/create/', views.MovieCreate.as_view(), name='movies_create'),
    path('movies/<int:pk>/update/', views.MovieUpdate.as_view(), name='movies_update'),
    path('movies/<int:pk>/delete/', views.MovieDelete.as_view(), name='movies_delete'),
    path('movies/<int:movies_id>/add_ratings/', views.add_ratings, name='add_ratings'),
    path('movies/<int:movies_id>/assoc_ratings/<int:ratings_id>/', views.assoc_ratings, name='assoc_ratings'),
    path('movies/<int:movies_id>/add_photo/', views.add_photo, name='add_photo'),
    path('ratings/', views.RatingsList.as_view(), name='ratings_index'),
    path('ratings/<int:pk>/', views.RatingsDetail.as_view(), name='ratings_detail'),
    path('ratings/create/', views.RatingsCreate.as_view(), name='ratings_create'),
    path('ratings/<int:pk>/update/', views.RatingsUpdate.as_view(), name='ratings_update'),
    path('ratings/<int:pk>/delete/', views.RatingsDelete.as_view(), name='ratings_delete'),
    path('accounts/signup/', main_app.signup, name='signup'),
]

moviecollector/moviecollector/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),  
    path('accounts/', include('django.contrib.auth.urls')),
]

moviecollector/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
RATES = (
    ('1', 'Loved it'),
    ('2', 'it is ok'),
    ('3', 'Fell asleep while watching')
)
class Movie(models.Model):
    title = models.CharField(max_length=100)
    year = models.IntegerField()
    actors = models.CharField(max_length=500)
    genre = models.TextField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={"movies_id":self.id})

class Ratings(models.Model):
    thoughts = models.CharField(max_length=500)
    rate = models.CharField(
        max_length=10,
        choices=RATES,
        default=RATES[0][0]
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_rate_display()} on {self.thoughts}"

class Photo(models.Model):
    url = models.CharField(max_length=300)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for movies_id: {self.movies_id} @{self.url}"

moviecollector/main_app/forms.py
from django.forms import ModelForm
from .models import Ratings

class RatingsForm(ModelForm):
    class Meta:
        model = Ratings
        fields = ['thoughts', 'rate']

    def __str__(self):
        return f"{self.get_rate_display()} on {self.thoughts}"

moviecollector/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RatingsForm
from django.views.generic import ListView, DetailView

from .models import Movie, Ratings, Photo
import uuid
import boto3

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'moviecollect-hn-89'


def home(request):
    return render(request, 'about.html')


def about(request):
    return render(request, 'about.html')


def movies_index(request):
    movies = Movie.objects.filter(user=request.user)
    return render(request, 'movies/index.html', {'Movie': movies})


def movies_detail(request, movies_id):
    movie = Movie.objects.get(id=movies_id)
    ratings_form = RatingsForm()
    return render(request, 'movies/detail.html', {'movies': movie, 'ratings_form': RatingsForm})
    
def add_ratings(request, movies_id):
    form = RatingsForm(request.POST)
    if form.is_valid():
        new_ratings = form.save(commit=False)
        new_ratings.movies_id = movies_id
        new_ratings.save()
    return redirect('detail', movies_id= movies_id)

def assoc_ratings(request, movies_id, ratings_id):
    Movie.objects.get(id=movies_id).ratings.add(ratings_id)
    return redirect('detail', movies_id=movies_id)


@login_required
def add_photo(request, movies_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, movies_id=movies_id)
            photo.save()
        except:
            print('An error occored while uploading file to S3')
    return redirect('detail', movies_id=movies_id)


class MovieCreate(LoginRequiredMixin, CreateView):
    model = Movie
    fields = ['title', 'year', 'actors', 'genre']
    success_url = '/movies/'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class MovieUpdate(UpdateView):
    model = Movie
    fields = ['title', 'year', 'actors', 'genre']


class MovieDelete(DeleteView):
    model = Movie
    success_url = '/movies/'

class RatingsList(ListView):
    model = Ratings

class RatingsDetail(DetailView):
    model = Ratings

class RatingsCreate(CreateView):
    model = Ratings
    fields = '__all__'

class RatingsUpdate(UpdateView):
    model = Ratings
    fields = ['thoughts', 'rate']

class RatingsDelete(DeleteView):
    model = Ratings
    success_url = '/ratings/'




def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
    else:
        error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

moviecollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<body>
    <h1>About The Movie Collector</h1>
    <p>My Favorite Movies! </p>
    <p>This has always been a dream to make a movies app. Where people can come and share their favorite movies!
</body>
{% endblock %}

moviecollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <title>Movie Collection</title>
  </head>
  <body>
    <nav class="navbar">
      <ul>
            <li><a href="/about">About</a></li>
            <li><a href="{% url 'movies_create' %}">Add a Movie</a></li>
            <li><a href="{% url 'index' %}">View All my Movies</a></li>
            <li><a href="{% url 'ratings_create' %}">Add a Rating</a></li>
            <li><a href="{% url 'ratings_index' %}">View All Ratings</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
      </ul> 
  </nav>
 </div>

</header>
<main class="container">
  {% block content %}
  {% endblock %}
</main>
<br><br>
<footer class="page-footer">
  <div class="right">All Rights Reserved, &copy; 2022 Movie Collector &nbsp;</div>
</footer>
</body>
</html>

moviecollector/main_app/templates/main_app/movie_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete A Movie</h1>

  <h4>Are you sure you want to delete? <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete NOW!" class="btn">
    <a href="{% url 'detail' movie.id %}">Cancel</a>
  </form>
{% endblock %}

moviecollector/main_app/templates/main_app/movie_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.title}}</span></h1>
{% else %}
<h1>Add New Movie</h1>
{% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

moviecollector/main_app/templates/main_app/ratings_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Ratings</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ ratings.thoughts }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'ratings_update' ratings.id %}">Edit</a>
        <a href="{% url 'ratings_delete' ratings.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

moviecollector/main_app/templates/main_app/ratings_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit <span class="black-text">{{object.title}}</span></h1>
    {% else %}
        <h1>Add Ratings</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit Rating!" class="btn">
    </form>
{% endblock %}

moviecollector/main_app/templates/main_app/ratings_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Ratings List</h1>


{% for ratings in ratings_list %}
  <a href="{% url 'ratings_detail' ratings.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ Ratings }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

moviecollector/main_app/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}

<H1>Movie Details</H1>

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ movies.title }}</span>
        <p>year: {{movies.year}}</p>
        <p>genre: {{ movies.genre }}</p>
        <p>actors: {{ movies.actors }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'movies_update' movies.id %}">Edit</a>
        <a href="{% url 'movies_delete' movies.id %}">Delete</a>
      </div>
</div>
<div class="col s6">
  <form action="{% url 'add_ratings' movies.id %}" method="post">
    {% csrf_token %}
    {{ ratings_form.as_p }}
    <input type="submit" class="btn" value="Add Ratings">
  </form>
    <table class="striped">
      <thead>
        <tr><th>Thoughts</th><th>Ratings</th></tr>
      </thead>
      <tbody>
        {% for ratings in movies.ratings_set.all %}
          <tr>
            <td>{{ratings.get_rate_display}}</td>
            <td>{{ratings.thoughts}}</td>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br><br>
 {% for photo in movie.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
 {% empty %}
    <div class="card-panel black-text center-align">No Photos Added</div>
 {% endfor %}
    <form action="{% url 'add_photo' movies.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
 {% csrf_token %}
 <input type="file" name="photo-file">
 <input type="submit" class="btn" value="Upload Photo">
</form>



{% endblock %}

moviecollector/main_app/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Movie List</h1>

{% for movies in Movie %} 
    <div class="card">
        <a href ="{% url 'detail' movies.id %}">
        <div class="card-content"> 
            <span class="card-title">{{ movies.title }}</span>
            <p>Year: {{ movies.year }}</p>
            <p>Actors: {{ movies.actors }}</p>
            <p>Genre: {{ movies.genre }}</p>
        </div>
        </a>
    </div>
{% endfor %}
{% endblock %}